[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "aux5"
version = "0.1.0"

[dependencies]
cortex-m = "0.4.3"

[dependencies.cortex-m-rt]
features = ["abort-on-panic"]
version = "0.3.13"

[dependencies.f3]
features = ["rt"]
version = "0.5.3"